### PR TITLE
Added GH testing

### PR DESCRIPTION
**Pull request by zzambers**
Added github testing using c-j-c-test.

### CODE REVIEW

**Comment by zzambers** [comment]
Fedora failures actually seem like legit failures (not problem with c-j-c-test).

**JDK 8**
```
Error: 
(try to add '--skip-broken' to skip uninstallable packages)
 Problem: conflicting requests
  - nothing provides libc.so.1()(64bit) needed by java-1.8.0-openjdk-src-1:1.8.0.372.b07-6.fc38.x86_64 from @commandline
  - nothing provides libc.so.1(SUNW_0.7)(64bit) needed by java-1.8.0-openjdk-src-1:1.8.0.372.b07-6.fc38.x86_64 from @commandline
```
I can reproduce broken dependencies of java-1.8.0-openjdk-src-1:1.8.0.372.b07-6.fc38.x86_64 locally in f38 VM.

**JDK 17**
Test with unmodified config files (by test) fails, because some config. files from new rpms are created .rpmnew. Seems like some config files has been changed in new rpms. However in this case, new files should still replace old ones (and not be created as .rpmnew) as long as old files have not been touched. This inconsistent with normal rpm [behaviour](https://www.cl.cam.ac.uk/~jw35/docs/rpm_config.html).
```
...
TEST: Update, config files unmodified
...
warning: /etc/java/java-17-openjdk/java-17-openjdk-17.0.7.0.7-5.fc38.x86_64/conf/security/java.security created as /etc/java/java-17-openjdk/java-17-openjdk-17.0.7.0.7-5.fc38.x86_64/conf/security/java.security.rpmnew
warning: /etc/java/java-17-openjdk/java-17-openjdk-17.0.7.0.7-5.fc38.x86_64/conf/security/nss.fips.cfg created as /etc/java/java-17-openjdk/java-17-openjdk-17.0.7.0.7-5.fc38.x86_64/conf/security/nss.fips.cfg.rpmnew
...
S.5....T.  c /etc/java/java-17-openjdk/java-17-openjdk-17.0.7.0.7-5.fc38.x86_64/conf/security/java.security
S.5....T.  c /etc/java/java-17-openjdk/java-17-openjdk-17.0.7.0.7-5.fc38.x86_64/conf/security/nss.fips.cfg
FAILED: Verifying installed files (new)
...
FAIL: File exists /etc/java/java-17-openjdk/java-17-openjdk-17.0.7.0.7-5.fc38.x86_64/conf/security/java.security.rpmnew !
...
FAILED: checking /etc/java/java-17-openjdk/${NVR_NEW}/conf/security/java.security
...
FAIL: File exists /etc/java/java-17-openjdk/java-17-openjdk-17.0.7.0.7-5.fc38.x86_64/conf/security/nss.fips.cfg.rpmnew !
...
FAILED: checking /etc/java/java-17-openjdk/${NVR_NEW}/conf/security/nss.fips.cfg
...
```

**Comment by zzambers** [comment]
I have created issue for JDK 17 problem: https://github.com/rh-openjdk/copy_jdk_configs/issues/2

**Comment by judovana** [comment]
Thanx for heads up!

yes, pls merge

**Comment by judovana** [comment]
The
```
nothing provides libc.so.1()(64bit) needed by java-1.8.0-openjdk-src-1:1.8.0.372.b07-6.fc38.x86_64 from @commandline
  - nothing provides libc.so.1(SUNW_0.7)(64bit) ne
 ```

was already ficed by:
https://src.fedoraproject.org/rpms/java-1.8.0-openjdk/pull-request/180

**Pull request merged**
